#
# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source
# tree and available online at
#
# http://www.dspace.org/license/
#

version: '3.7'
networks:
  dspacenet:
services:
  dspace-angular:
    restart: unless-stopped
    container_name: dspace-angular${INSTANCE}
    environment:
      TZ: ${TIMEZONE:-Europe/Bratislava}
      DSPACE_UI_SSL: 'false'
      DSPACE_UI_HOST: dspace-angular
      DSPACE_UI_PORT: 4000
      DSPACE_UI_NAMESPACE: /
      DSPACE_REST_SSL: ${DSPACE_SSL:-false}
      DSPACE_REST_HOST: ${DSPACE_HOST:-localhost}
      DSPACE_REST_PORT: ${DSPACE_REST_PORT}
      DSPACE_REST_NAMESPACE: /server
    image: ${DSPACE_UI_IMAGE:-dataquest/dspace-angular:dspace-7_x}
    volumes:
    - ./config.prod.yml:/app/config/config.prod.yml
    build:
      context: ..
      dockerfile: Dockerfile
    networks:
      dspacenet:
    entrypoint: ${FE_CMD:-/bin/sh -c "pm2-runtime start dspace-ui.json > /dev/null 2> /dev/null"}
    ports:
    - published: 400${INSTANCE}
      target: 4000
      host_ip: 127.0.0.1
    - published: 987${INSTANCE}
      target: 987${INSTANCE}
      host_ip: 127.0.0.1
    stdin_open: true
    tty: true
