services:
  db:
    image: mariadb
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    container_name: mdb
    environment:
      MARIADB_ROOT_PASSWORD: ${MATOMO_MARIADB_ROOT_PASSWORD:-example}
      MARIADB_AUTO_UPGRADE: ${MATOMO_MARIADB_AUTO_UPGRADE:--1}
      MARIADB_INITDB_SKIP_TZINFO: ${MATOMO_MARIADB_INITDB_SKIP_TZINFO:-1}

  gui:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8148:80
    container_name: matomo_phpAdmin
    restart: always
    links:
      - "db:db"

  matomo:
    image: matomo
    container_name: matomo_statistics
    restart: always
    environment:
      MYSQL_PASSWORD: ${MATOMO_MYSQL_PASSWORD:-example}
      MYSQL_DATABASE: ${MATOMO_MYSQL_DATABASE:-matomo_statistics}
      MYSQL_USER: ${MATOMO_MYSQL_USER:-root}
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_HOST: db
      MATOMO_DATABASE_USERNAME: ${MATOMO_DATABASE_USERNAME:-root}
      MATOMO_DATABASE_PASSWORD: ${MATOMO_DATABASE_PASSWORD:-example}
      MATOMO_DATABASE_DBNAME: ${MATOMO_DATABASE_DBNAME:-matomo_statistics}
    ports:
      - 8135:80
