name: create_bitstreams - import test files

on:
  workflow_dispatch:
    inputs:
      INSTANCE:
        required: true
        default: '8'
        type: choice
        options:
          - '2'
          - '5'
          - '6'
          - '8'
      
jobs:

  checkout-codebase:
    runs-on: dspace-dep-1
    steps:
      - uses: actions/checkout@v4
        with:
          repository: dataquest-dev/dspace-rest-test
          ref: master
          submodules: 'recursive'

  import:

    strategy:
      matrix:
        include:
          - instance: '2'
            runner: dspace-dep-1
          - instance: '5'
            runner: dspace-dep-1
          - instance: '6'
            runner: dspace-dep-1
          - instance: '8'
            runner: dspace-dep-1
              
    needs: checkout-codebase

    

    runs-on: ${{ matrix.runner }}
    env:
      DSPACE_REST_API: http://dev-5.pc:8${{ matrix.instance }}/server/api/
    steps:
      - name: install requirements and run import
        if: github.event.inputs.INSTANCE == matrix.instance
        run: |
          pip install -r requirements.txt
          cd tests/integration
          python3 create_bitstreams.py
